defaults:
  expname: basis_image
  logdir: ./logs

  mode: 'images'

  ckpt: null                  # help='specific weights npy file to reload for coarse network'

model:
  basis_dims: [32,32,32,16,16,16]
  # basis_resos: [32,51,70,89,108,128]
  # basis_resos: [16,26,35,45,54,64]
  basis_resos: [8,13,19,23,27,32]
  # freq_bands: [2. , 3.2, 4.4, 5.6, 6.8, 8.]
  # freq_bands: [4. , 6.4, 8.8, 11.2, 13.6, 16.]
  # freq_bands: [8. , 12.8, 17.6, 22.4, 27.2, 32.]
  coeff_reso: [20, 12]
  
  coef_init: 0.001

  coef_mode: bilinear
  basis_mode: bilinear

  coeff_type: 'grid'
  basis_type: 'grid'

  in_dim: 2
  out_dim: 2
  num_layers: 2
  hidden_dim: 64
  with_dropout: True

#dataset:
  # loader options
  #dataset_name: images 
  #datadir: /bmrc-homes/nmrgrp/nmr219/ese5934_project/data/data/file1002570.h5

training:
  n_iters: 300000
  batch_size: 40960

  # learning rate
  lr_small: 0.002
  lr_large: 0.002